---
- name: Deploy web
  shell: |
    {{ openshift_cli }} get svc web-spring -n coolstore || \
    ( \
      {{ openshift_cli }} apply -f <({{ istio_ctl }} kube-inject {{ istio_options }} -f files/web-deployment.yml) -n coolstore && \
      {{ openshift_cli }} create -f files/web-service.yml -n coolstore; \
      {{ openshift_cli }} expose svc/web-spring -n coolstore; \
      {{ openshift_cli }} env deployment/web-spring  -n coolstore-{{ project_suffix }} --overwrite \
              COOLSTORE_GW_ENDPOINT="gateway-spring-coolstore" \
              HOSTNAME_HTTP="web-spring:8080";
    )
  args:
    executable: /bin/bash