---
# Common Facts for the project
- name: Check if infra project exists
  shell: "{{ openshift_cli }} get projects | grep -q {{ infra_project }}"
  register: cmd_infra_project_exists
  failed_when: false
  changed_when: false

- set_fact:
    infra_project_exists: true
  when: cmd_infra_project_exists is succeeded

- set_fact:
    infra_project_exists: false
  when: cmd_infra_project_exists is failed
   
- name: Check if nexus is alread installed
  shell: "{{ openshift_cli }} get service nexus -n {{ infra_project }}"
  register: cmd_nexus_svc_exists
  failed_when: false
  changed_when: false

- set_fact:
    nexus_svc_exists: true
  when: cmd_nexus_svc_exists is succeeded

- set_fact:
    nexus_svc_exists: false
  when: cmd_nexus_svc_exists is failed


