apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gateway
    version: spring
  name: gateway-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      version: spring
  template:
    metadata:
      labels:
        app: gateway
        version: spring
    spec:
      containers:
      - name: gateway-spring
        env:
        - name: JAVA_OPTIONS
          value: -Xms128m -Xmx256m -Dspring.profiles.active=openshift -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:///dev/./urandom
        - name: JAEGER_SERVICE_NAME
          value: gateway-spring
        - name: JAEGER_ENDPOINT
          value: http://jaeger-collector.istio-system.svc:14268/api/traces
        - name: JAEGER_PROPAGATION
          value: b3
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: 10
        image: coolstore/gateway-spring:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        securityContext:
          privileged: false
