apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: coolstore-ingress
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /api/products
        backend:
          serviceName: gateway
          servicePort: http
  - http:
        paths:
        - backend:
            serviceName: web
            servicePort: http