apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: web
    version: v1
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: v1
  template:
    metadata:
      labels:
        app: web
        version: v1
    spec:
      containers:
      - env:
        - name: COOLSTORE_GW_ENDPOINT
          value: gateway-coolstore-spring
        - name: HOSTNAME_HTTP
          value: web:8080
        image: docker.io/coolstore/web:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/index.html
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        name: web
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/index.html
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        securityContext:
          privileged: false
